name: server
description: This is your server code.

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  socky_server:
    path: ../../../socky_server
  http: ^0.12.0+4
  getbykey: ^1.0.1

  # Contains dart code which is shared between server and app
  shared:
    path: ../shared

dev_dependencies:
  build_runner: ^1.0.0
  socky_builder:
    path: ../../../socky_builder
