name: shared
description: This package contains dart code which is shared between server and app

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  uuid: ^2.1.0

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.3.0
